# Generated by Django 5.2.4 on 2025-07-07 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cherepitsa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Изображение')),
                ('specifications', models.TextField(blank=True, verbose_name='Характеристики')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('razmer_gabaritnyy_ryadnoy', models.CharField(blank=True, max_length=100, verbose_name='Размеры (габаритные) рядной черепицы')),
                ('razmer_kroynoy_ryadnoy', models.CharField(blank=True, max_length=100, verbose_name='Размер (кроющий) рядной черепицы')),
                ('razmer_gabaritnyy_konkovoy', models.CharField(blank=True, max_length=100, verbose_name='Размер (габаритные) коньковой черепицы')),
                ('razmer_kroynoy_konkovoy', models.CharField(blank=True, max_length=100, verbose_name='Размер (кроющей) коньковой черепицы')),
                ('massa_ryadnoy', models.CharField(blank=True, max_length=100, verbose_name='Масса рядной черепицы')),
                ('chislo_ryadnoy_na_kvadrat', models.CharField(blank=True, max_length=100, verbose_name='Число черепицы на 1 кв.м (рядной)')),
                ('chislo_konkovoy_na_kvadrat', models.CharField(blank=True, max_length=100, verbose_name='Число черепицы на 1 кв.м (коньковой)')),
                ('temperaturnyy_diapazon', models.CharField(default='от -60 до +120', max_length=100, verbose_name='Температурный диапазон')),
            ],
            options={
                'verbose_name': 'Черепица',
                'verbose_name_plural': 'Черепица',
            },
        ),
        migrations.CreateModel(
            name='Dozhdiepriemnik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Изображение')),
                ('specifications', models.TextField(blank=True, verbose_name='Характеристики')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('naruzhnyy_razmer', models.CharField(blank=True, max_length=100, verbose_name='Наружный размер')),
                ('vysota', models.CharField(blank=True, max_length=100, verbose_name='Высота')),
                ('vnutrenniy_diametr', models.CharField(blank=True, max_length=100, verbose_name='Внутренний диаметр')),
                ('glubina_ustanovki_kryshki', models.CharField(blank=True, max_length=100, verbose_name='Глубина установки крышки')),
                ('nominalnaya_nagruzka', models.CharField(blank=True, max_length=100, verbose_name='Номинальная нагрузка')),
                ('ves', models.CharField(blank=True, max_length=100, verbose_name='Вес')),
            ],
            options={
                'verbose_name': 'Дождеприемник',
                'verbose_name_plural': 'Дождеприемники',
            },
        ),
        migrations.CreateModel(
            name='Lyuk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Изображение')),
                ('specifications', models.TextField(blank=True, verbose_name='Характеристики')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('naruzhnyy_razmer', models.CharField(blank=True, max_length=100, verbose_name='Наружный размер')),
                ('vysota', models.CharField(blank=True, max_length=100, verbose_name='Высота')),
                ('vnutrenniy_diametr', models.CharField(blank=True, max_length=100, verbose_name='Внутренний диаметр')),
                ('glubina_ustanovki_kryshki', models.CharField(blank=True, max_length=100, verbose_name='Глубина установки крышки')),
                ('nominalnaya_nagruzka', models.CharField(blank=True, max_length=100, verbose_name='Номинальная нагрузка')),
                ('ves', models.CharField(blank=True, max_length=100, verbose_name='Вес')),
                ('tip_vesa', models.CharField(choices=[('Легкий', 'Легкий'), ('Средний', 'Средний'), ('Тяжелый', 'Тяжелый')], max_length=50, verbose_name='Тип по весу')),
            ],
            options={
                'verbose_name': 'Люк',
                'verbose_name_plural': 'Люки',
            },
        ),
        migrations.CreateModel(
            name='TrotuarnayaPlitka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Изображение')),
                ('specifications', models.TextField(blank=True, verbose_name='Характеристики')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('razmery', models.CharField(blank=True, max_length=100, verbose_name='Размеры')),
                ('vysota', models.CharField(blank=True, max_length=100, verbose_name='Высота')),
                ('kolichestvo_na_km', models.CharField(blank=True, max_length=100, verbose_name='Количество на 1 к.м')),
            ],
            options={
                'verbose_name': 'Тротуарная плитка',
                'verbose_name_plural': 'Тротуарная плитка',
            },
        ),
        migrations.CreateModel(
            name='VodootvodnyyLotok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Изображение')),
                ('specifications', models.TextField(blank=True, verbose_name='Характеристики')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('naruzhnyy_razmer_lotka', models.CharField(blank=True, max_length=100, verbose_name='Наружный размер лотка')),
                ('vysota', models.CharField(blank=True, max_length=100, verbose_name='Высота')),
                ('nominalnaya_nagruzka', models.CharField(blank=True, max_length=100, verbose_name='Номинальная нагрузка')),
                ('naruzhnyy_razmer_reshetki_lotka', models.CharField(blank=True, max_length=100, verbose_name='Наружный размер решетки лотка')),
                ('ves', models.CharField(blank=True, max_length=100, verbose_name='Вес')),
            ],
            options={
                'verbose_name': 'Водоотводный лоток',
                'verbose_name_plural': 'Водоотводные лотки',
            },
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
